#spring.application.name=SpringJPA
server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/Spring}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "EybNcJq0VGrjTqwq/gSUK/vK1vVjD+/qWUI+AXThh88WEe78NGz9Tyvv64jagvpQ"
  valid-duration: 3600 #in seconds
  refreshable-duration: 360000 #in seconds
